import type {Metadata} from 'next';
import localFont from 'next/font/local';
import React from 'react';
import AppHeader from '@/app/[locale]/AppHeader';
import {AppRouterCacheProvider} from '@mui/material-nextjs/v15-appRouter';
import {
  Box,
  CssBaseline,
  StyledEngineProvider,
  ThemeProvider,
  Toolbar,
} from '@mui/material';
import {darkTheme} from '@/theme';
import {Roboto} from 'next/font/google';
import {Defaults} from '@/appDefaults';
import WrappedCookiesProvider from '@/components/WrappedCookiesProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'DHBW Verzeichnis',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <AppRouterCacheProvider options={{enableCssLayer: true}}>
          <StyledEngineProvider>
            <ThemeProvider theme={darkTheme}>
              <WrappedCookiesProvider
                defaultSetOptions={{secure: true, sameSite: 'lax', path: '/'}}
              >
                {children}
              </WrappedCookiesProvider>
            </ThemeProvider>
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
